# Generated by Django 5.0.1 on 2024-01-28 13:35

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0003_alter_hotel_location_delete_location'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='hotel',
            managers=[
                ('prod', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ImageGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagegallery', models.ImageField(upload_to='hotelroom_gallery')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsApp.hotel')),
            ],
        ),
    ]
