# Generated by Django 5.0.1 on 2024-01-28 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0004_alter_hotel_managers_imagegallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rcategory', models.CharField(choices=[('KIN', 'KING'), ('QUE', 'QUEEN'), ('NAC', 'NON-AC'), ('AC', 'AC'), ('DEL', 'DELUX')], max_length=3)),
                ('beds', models.IntegerField()),
                ('capacity', models.IntegerField()),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsApp.hotel')),
            ],
        ),
    ]
