# Generated by Django 5.0.1 on 2024-01-30 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0007_remove_booking_hotel_booking_room_booking_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='capacity',
            new_name='max_capacity',
        ),
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='rcategory',
            field=models.CharField(choices=[('AC', 'AC'), ('KING', 'KING'), ('NON-AC', 'NON-AC'), ('DELUX', 'DELUX'), ('QUEEN', 'QUEEN')], max_length=10),
        ),
    ]
