# Generated by Django 5.0.1 on 2024-01-30 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0008_rename_capacity_room_max_capacity_room_room_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='max_capacity',
            new_name='capacity',
        ),
        migrations.AlterField(
            model_name='room',
            name='rcategory',
            field=models.CharField(choices=[('DELUX', 'DELUX'), ('KING', 'KING'), ('QUEEN', 'QUEEN'), ('NON-AC', 'NON-AC'), ('AC', 'AC')], max_length=10),
        ),
    ]
