# Generated by Django 5.0.1 on 2024-01-30 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0009_rename_max_capacity_room_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='hotel',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
