# Generated by Django 5.0.1 on 2024-01-30 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0012_alter_room_room_category_alter_room_room_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_category',
            field=models.CharField(choices=[('AC', 'AC'), ('QUEEN', 'QUEEN'), ('KING', 'KING'), ('NON-AC', 'NON-AC'), ('DELUX', 'DELUX')], max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_price',
            field=models.IntegerField(),
        ),
    ]
