# Generated by Django 5.0.1 on 2024-01-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0013_alter_room_room_category_alter_room_room_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='beds',
        ),
        migrations.AddField(
            model_name='room',
            name='ac_room',
            field=models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC')], default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_category',
            field=models.CharField(choices=[('Queen Room', 'Queen Room'), ('Double-Double Room', 'Double-Double Room'), ('Double Room', 'Double Room'), ('Twin Room', 'Twin Room'), ('King Room', 'King Room'), ('Single Room', 'Single Room')], max_length=20),
        ),
    ]
