# Generated by Django 5.0.1 on 2024-01-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0015_alter_room_managers_alter_room_ac_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phoneNo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='ac_room',
            field=models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC')], default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_category',
            field=models.CharField(choices=[('Twin Room', 'Twin Room'), ('Queen Room', 'Queen Room'), ('Double Room', 'Double Room'), ('King Room', 'King Room'), ('Double-Double Room', 'Double-Double Room'), ('Single Room', 'Single Room')], max_length=20),
        ),
    ]
