# Generated by Django 5.0.1 on 2024-01-31 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0016_profile_phoneno_alter_room_ac_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_available',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='max_capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_category',
            field=models.CharField(choices=[('King Room', 'King Room'), ('Double-Double Room', 'Double-Double Room'), ('Single Room', 'Single Room'), ('Twin Room', 'Twin Room'), ('Double Room', 'Double Room'), ('Queen Room', 'Queen Room')], max_length=20),
        ),
        migrations.CreateModel(
            name='CheckAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('num_guests', models.PositiveIntegerField()),
                ('num_rooms', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default='False')),
                ('room', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='hmsApp.room')),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
