# Generated by Django 5.0.1 on 2024-02-01 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0018_checkavailable_user_alter_room_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='ac_room',
            field=models.CharField(choices=[('Non-AC', 'Non-AC'), ('AC', 'AC')], default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_category',
            field=models.CharField(choices=[('Twin Room', 'Twin Room'), ('Queen Room', 'Queen Room'), ('King Room', 'King Room'), ('Single Room', 'Single Room'), ('Double Room', 'Double Room'), ('Double-Double Room', 'Double-Double Room')], max_length=20),
        ),
        migrations.DeleteModel(
            name='CheckAvailable',
        ),
    ]
