# Generated by Django 5.0.1 on 2024-02-01 01:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0019_alter_room_ac_room_alter_room_room_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='ac_room',
            field=models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC')], default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_category',
            field=models.CharField(choices=[('Double Room', 'Double Room'), ('Queen Room', 'Queen Room'), ('King Room', 'King Room'), ('Twin Room', 'Twin Room'), ('Double-Double Room', 'Double-Double Room'), ('Single Room', 'Single Room')], max_length=20),
        ),
        migrations.CreateModel(
            name='CheckAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_out_date', models.DateField()),
                ('num_guests', models.PositiveIntegerField()),
                ('num_rooms', models.PositiveIntegerField()),
                ('is_available', models.BooleanField(default='False')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='hmsApp.room')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
