# Generated by Django 5.0.1 on 2024-02-09 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0020_alter_room_ac_room_alter_room_room_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkavailable',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='checkavailable',
            name='is_available',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_available',
        ),
        migrations.AddField(
            model_name='checkavailable',
            name='booking_id',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('1', 'available'), ('2', 'not available')], default=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='room',
            name='ac_room',
            field=models.CharField(choices=[('Non-AC', 'Non-AC'), ('AC', 'AC')], default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_category',
            field=models.CharField(choices=[('Double-Double Room', 'Double-Double Room'), ('Twin Room', 'Twin Room'), ('Single Room', 'Single Room'), ('King Room', 'King Room'), ('Queen Room', 'Queen Room'), ('Double Room', 'Double Room')], max_length=20),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Booking_id', models.CharField(max_length=50)),
                ('num_rooms', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('is_completed', models.BooleanField(default='False')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsApp.hotel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsApp.room')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
