# Generated by Django 5.0.1 on 2024-02-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0021_remove_checkavailable_date_added_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='ac_room',
            field=models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC')], default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_category',
            field=models.CharField(choices=[('King Room', 'King Room'), ('Double-Double Room', 'Double-Double Room'), ('Queen Room', 'Queen Room'), ('Single Room', 'Single Room'), ('Double Room', 'Double Room'), ('Twin Room', 'Twin Room')], max_length=20),
        ),
    ]
