# Generated by Django 5.0.1 on 2024-02-10 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0022_alter_room_ac_room_alter_room_room_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkavailable',
            name='num_rooms',
        ),
        migrations.AlterField(
            model_name='room',
            name='ac_room',
            field=models.CharField(choices=[('Non-AC', 'Non-AC'), ('AC', 'AC')], default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_category',
            field=models.CharField(choices=[('Double-Double Room', 'Double-Double Room'), ('Single Room', 'Single Room'), ('Double Room', 'Double Room'), ('Queen Room', 'Queen Room'), ('Twin Room', 'Twin Room'), ('King Room', 'King Room')], max_length=20),
        ),
    ]
