# Generated by Django 5.0.1 on 2024-02-10 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0023_remove_checkavailable_num_rooms_alter_room_ac_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Booking_id',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='num_rooms',
        ),
        migrations.AddField(
            model_name='booking',
            name='checkavailable',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='hmsApp.checkavailable'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_category',
            field=models.CharField(choices=[('Twin Room', 'Twin Room'), ('Single Room', 'Single Room'), ('Double-Double Room', 'Double-Double Room'), ('Double Room', 'Double Room'), ('King Room', 'King Room'), ('Queen Room', 'Queen Room')], max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
