# Generated by Django 5.0.1 on 2024-02-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0024_remove_booking_booking_id_remove_booking_num_rooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='checkavailable',
        ),
        migrations.AddField(
            model_name='booking',
            name='num_guests',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_category',
            field=models.CharField(choices=[('Double-Double Room', 'Double-Double Room'), ('Queen Room', 'Queen Room'), ('King Room', 'King Room'), ('Twin Room', 'Twin Room'), ('Double Room', 'Double Room'), ('Single Room', 'Single Room')], max_length=20),
        ),
    ]
