# Generated by Django 5.0.1 on 2024-02-10 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0025_remove_booking_checkavailable_booking_num_guests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='num_guests',
        ),
        migrations.AddField(
            model_name='booking',
            name='checkavailable',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='hmsApp.checkavailable'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_category',
            field=models.CharField(choices=[('King Room', 'King Room'), ('Single Room', 'Single Room'), ('Queen Room', 'Queen Room'), ('Double Room', 'Double Room'), ('Twin Room', 'Twin Room'), ('Double-Double Room', 'Double-Double Room')], max_length=20),
        ),
    ]
