# Generated by Django 5.0.1 on 2024-02-10 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0026_remove_booking_num_guests_booking_checkavailable_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='checkavailable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hmsApp.checkavailable'),
        ),
        migrations.AlterField(
            model_name='room',
            name='ac_room',
            field=models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC')], default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_category',
            field=models.CharField(choices=[('King Room', 'King Room'), ('Double Room', 'Double Room'), ('Double-Double Room', 'Double-Double Room'), ('Twin Room', 'Twin Room'), ('Queen Room', 'Queen Room'), ('Single Room', 'Single Room')], max_length=20),
        ),
    ]
