# Generated by Django 5.0.1 on 2024-02-10 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0027_alter_booking_checkavailable_alter_room_ac_room_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='checkavailable',
        ),
        migrations.AddField(
            model_name='booking',
            name='num_guests',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_category',
            field=models.CharField(choices=[('Queen Room', 'Queen Room'), ('Twin Room', 'Twin Room'), ('Double-Double Room', 'Double-Double Room'), ('Single Room', 'Single Room'), ('King Room', 'King Room'), ('Double Room', 'Double Room')], max_length=20),
        ),
    ]
