# Generated by Django 5.0.1 on 2024-02-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0028_remove_booking_checkavailable_booking_num_guests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='ac_room',
            field=models.CharField(choices=[('Non-AC', 'Non-AC'), ('AC', 'AC')], default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_category',
            field=models.CharField(choices=[('Double Room', 'Double Room'), ('Single Room', 'Single Room'), ('Double-Double Room', 'Double-Double Room'), ('Twin Room', 'Twin Room'), ('Queen Room', 'Queen Room'), ('King Room', 'King Room')], max_length=20),
        ),
    ]
