# Generated by Django 5.0.1 on 2024-02-10 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hmsApp', '0029_alter_room_ac_room_alter_room_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_category',
            field=models.CharField(choices=[('Single Room', 'Single Room'), ('King Room', 'King Room'), ('Double Room', 'Double Room'), ('Queen Room', 'Queen Room'), ('Double-Double Room', 'Double-Double Room'), ('Twin Room', 'Twin Room')], max_length=20),
        ),
    ]
